# Generated by Django 2.0.4 on 2018-04-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('building_number', models.CharField(max_length=32)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AptPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_rent', models.IntegerField()),
                ('amenitized_rent', models.IntegerField()),
                ('available_date', models.DateField()),
                ('queried_at', models.DateTimeField()),
                ('is_promotion', models.BooleanField(default=False)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eaves.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('custom_name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('eaves_id', models.CharField(max_length=32)),
                ('size', models.IntegerField()),
                ('image_url', models.CharField(max_length=2048)),
                ('code_name', models.CharField(max_length=32)),
                ('bedroom_type', models.CharField(max_length=32)),
                ('custom_name', models.CharField(default='', max_length=32)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eaves.Community')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eaves.FloorPlan'),
        ),
    ]
